CUDA_VISIBLE_DEVICES=0 python /home/wuhao/jobspace/robomimic/robomimic/scripts/train_adaptive.py \
    --agent /home/wuhao/jobspace/robomimic.wh/wuhao/ckpt/dp/low_dim_tool_hang/20260123043153/models/model_epoch_12.pth \
    --max_chunk_len 32 \
    --reward_offset 0.0 \
    --resample_penalty -0.005 \
    --total_timesteps 200000 \
    --n_steps 256 \
    --n_envs 8 \
    --batch_size 256 \
    --log_dir /home/wuhao/jobspace/robomimic/wuhao/adaptive_rl_results/tb_logs/standard_test_32 \
    --ckpt_dir /home/wuhao/jobspace/robomimic/wuhao/adaptive_rl_results/checkpoints/standard_test_32 \
    --save_videos