CUDA_VISIBLE_DEVICES=2 python /home/wuhao/jobspace/robomimic/robomimic/scripts/train_adaptive.py \
    --agent /home/wuhao/jobspace/robomimic/wuhao/ckpt/dp/low_dim_tool_hang/20260121084406/models/model_epoch_10_low_dim_v15_success_0.18.pth \
    --max_chunk_len 16 \
    --reward_offset 0.0 \
    --resample_penalty -0.005 \
    --total_timesteps 100000 \
    --n_steps 8 \
    --n_envs 8 \
    --batch_size 8 \
    --log_dir /home/wuhao/jobspace/robomimic/wuhao/adaptive_rl_results/tb_logs/success_test \
    --ckpt_dir /home/wuhao/jobspace/robomimic/wuhao/adaptive_rl_results/checkpoints/success_test